spring.datasource.url=jdbc:postgresql://localhost:5432/diario_db
spring.datasource.username=postgres
spring.datasource.password=diario_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=PpJptoDtPnjpDlomPjJ8nJjngX7zEE6hnLcoRxb8OkU=
jwt.expiration=86400000


